### ISSUE TITLE
Terraform Crash following provider update 109

### ISSUE THREAD

**Issue by hobovirtual** [vmware-archive/legacy-terraform-provider-vra7#110]
[crash.log](https://github.com/vmware/terraform-provider-vra7/files/2633917/crash.log)
[vra-terraform.log](https://github.com/vmware/terraform-provider-vra7/files/2633918/vra-terraform.log)

After updating provider with latest commit terraform apply is crashing with the same declaration file on centOS 7.5

Terraform apply

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

terraform -v
Terraform v0.11.8
+ provider.vra7 (unversioned)

go version
go version go1.11.2 linux/amd64

vRealize Automation 7.5

Declaration

```
provider "vra7" {
  username = "${var.vra_username}"
  password = "${var.vra_password}"
  tenant   = "${var.vra_tenant}"
  host     = "${var.vra_host}"
  insecure = true
}

//Component profile blueprint
resource "vra7_resource" "deployment1" {
  count = 1
  catalog_name = "Request Virtual Machine"
  wait_timeout = 30

  resource_configuration = {
  }

  catalog_configuration = {
    reasons = "Test"
    description = "deployment via terraform"
  }
}
```

Please see attach logs

**Comment by hobovirtual** [comment]
Please note also tried after updating terraform with same result

terraform -v
Terraform v0.11.10
+ provider.vra7 (unversioned)

**Comment by markpeek** [comment]
I'm assuming you built after upgrading to this [commit](#109 c56915cd5b41ad8b37a6eb77e710ecb2fcdf65f4). This moved away from using vendored code or a GOPATH environment. I've seen that crash before and I believe it has to do with a mismatch of terraform code between terraform and a plugin (likely in your GOPATH). Two things you could try to work around it. 1) clone this code outside of your GOPATH and build it again or 2) build it with this environment variable set (GO111MODULE=on).

**Comment by hobovirtual** [comment]
Hi @markpeek 

Tried the following with same results

Delete current GOPATH content and reconfigure
export GO111MODULE=on
New build in alternate GOPATH

```panic: Unknown validation type: 6
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: goroutine 28 [running]:
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.validateMapValues(0xe80655, 0x15, 0xc0002f0900, 0xc0002b74a0, 0xc0002f0900, 0xc00000f410, 0x195, 0xc0002fc158, 0xc0000dd2d8, 0x4148a5)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1478 +0xb7e
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateMap(0xc0002b9350, 0xe80655, 0x15, 0xceb8e0, 0xc0002e4cc0, 0xc0002b74a0, 0xc0002f0750, 0xc0002f08a0, 0xc0002fa700, 0xc0002fa700, ...)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1430 +0x590
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc0002b9350, 0xe80655, 0x15, 0xceb8e0, 0xc0002e4cc0, 0xc0002b74a0, 0xc0002f0750, 0x0, 0x0, 0x0, ...)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1629 +0x5c1
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc0002b9350, 0xe80655, 0x15, 0xc0002b74a0, 0xc0002f0750, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1274 +0x1f0
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc0002b9350, 0x0, 0x0, 0xc0002b9350, 0xc0002f0750, 0x28, 0xc000089cb0, 0xdaa0a0, 0xc0002fa1e0, 0x40b01f, ...)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:1526 +0x1c7
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc0002b9350, 0xc0002f0750, 0xe79a23, 0xc000273c80, 0xd, 0xdaa001, 0xc0002fa1e0, 0xe09140)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/schema.go:621 +0x46
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc0000cf980, 0xc0002f0750, 0xc000273c80, 0xd, 0xc0002de158, 0xdaa001, 0x0, 0xc0002da500)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/resource.go:368 +0x42
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc0002d6540, 0xc000273c80, 0xd, 0xc0002f0750, 0x203000, 0xc0002b4de0, 0x0, 0xc0002b4de0, 0x0, 0xeaf200)
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0x1a7
2018-11-30T19:03:15.048Z [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ValidateResource(0xc000281de0, 0xc0002e49e0, 0xc0002f0930, 0x0, 0x0)
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7:        /tmp/TerraformPluginProject/src/github.com/hashicorp/terraform/plugin/resource_provider.go:505 +0x6e
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7: reflect.Value.call(0xc0002b4de0, 0xc00000f0a8, 0x13, 0xe71adc, 0x4, 0xc000068f18, 0x3, 0x3, 0xc00016b700, 0x414f37, ...)
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7:        /usr/local/go/src/reflect/value.go:447 +0x449
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7: reflect.Value.Call(0xc0002b4de0, 0xc00000f0a8, 0x13, 0xc000052718, 0x3, 0x3, 0x12a05f200, 0xc000052710, 0xc0000527b8)
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7:        /usr/local/go/src/reflect/value.go:308 +0xa4
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7: net/rpc.(*service).call(0xc0002da440, 0xc000097f90, 0xc0002731c0, 0xc0002731d0, 0xc0002e0100, 0xc0002e4460, 0xcce3c0, 0xc0002e49e0, 0x16, 0xcce400, ...)
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7:        /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7: created by net/rpc.(*Server).ServeCodec
2018-11-30T19:03:15.049Z [DEBUG] plugin.terraform-provider-vra7:        /usr/local/go/src/net/rpc/server.go:481 +0x47e
2018-11-30T19:03:15.049Z [DEBUG] plugin: plugin process exited: path=/tmp/TerraformPluginProject/bin/terraform-provider-vra7



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues
```

**Comment by Prativa20** [comment]
I built my code with the latest code in GOPATH/src (as before) and export GO111MODULE=on. It works for me.

Go version to: go version go1.11.2 darwin/amd64
Terraform version: Terraform v0.11.7

**Comment by markpeek** [comment]
I tried reproducing and it worked fine for me as well.

@hobovirtual you appear to be using Linux (CentOS 7.5 per above comment). The crash log is showing the terraform binary is being run out of "/usr/bin/terraform" and there is a plugin override coming from a .terraformrc file mapping the vra7 provider to "/root/TerraformPluginProject/bin/terraform-provider-vra7". Is that the correct location for the latest provider you compiled?

**Comment by hobovirtual** [comment]
Hi @markpeek 

It's exactly right, my provider is located on this install under my home folder, root for this lab machine.

Will try to debug more and re-revalidate my installation

**Comment by hobovirtual** [comment]
Hi @markpeek  and @Prativa20 

Finally made it work

During the go build i receveived the following error

```
# net
exec: "gcc": executable file not found in $PATH
```

By adding the following along the GO111MODULE=on, i was able to complete the package build

`export CGO_ENABLED=0`

vra7 terraform provider now works as expected. 
Seems to be a known or at least frequent issue with go 1.11.x
