### ISSUE TITLE
Terraform Crash 

### ISSUE THREAD

**Issue by ymmit85** [vmware-archive/legacy-terraform-provider-vra7#164]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!

terraform init completes, but terraform init/apply both cause a crash.
Similar to other reported issues were if catalog_configuration or resource_configuration are removed from the config terraform plan will work, however this is not ideal as we require customization of the requests.

This is tested with following versions..

-go version go1.11.4 windows/amd64
-Terraform v0.11.14
+ provider.vra7 (unversioned)

Log output as follows..

Error: vra7_deployment.my_vra7_deployment: unexpected EOF

panic: Unknown validation type: 6
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: goroutine 10 [running]:
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.validateMapValues(0xfe30e2, 0x16, 0xc00032d350, 0xc000123a00, 0xc00032d350, 0xc00049c100, 0x195, 0xc0000ae5a8, 0xc0005172d8, 0x4130a5)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:1613 +0xb85
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.schemaMap.validateMap(0xc000083cb0, 0xfe30e2, 0x16, 0xe13b20, 0xc00013abe0, 0xc000123a00, 0xc00032ced0, 0xc00032d0b0, 0xc00033e9f0, 0xc00033e9f0, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:1565 +0x597
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc000083cb0, 0xfe30e2, 0x16, 0xe13b20, 0xc00013abe0, 0xc000123a00, 0xc00032ced0, 0x0, 0x0, 0x0, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:1777 +0x5c8
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc000083cb0, 0xfe30e2, 0x16, 0xc000123a00, 0xc00032ced0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:1382 +0x21b
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc000083cb0, 0x0, 0x0, 0xc000083cb0, 0xc00032ced0, 0x28, 0xc000083ec0, 0xeec880, 0xc00033e240, 0x409386, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:1661 +0x1ce
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc000083cb0, 0xc00032ced0, 0xfdbb95, 0xc000130250, 0xf, 0xeec801, 0xc00033e240, 0xf58aa0)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/schema.go:677 +0x4d
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc000108000, 0xc00032ced0, 0xc000130250, 0xf, 0xc000142638, 0xeec801, 0x8, 0xee1840)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/resource.go:357 +0x49
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc000108080, 0xc000130250, 0xf, 0xc00032ced0, 0xc00033e240, 0xc000130248, 0x0, 0xc0000f3080, 0x0, 0xeee700)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x1ae
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ValidateResource(0xc0004980a0, 0xc00013a4c0, 0xc00012c2a0, 0x0, 0x0)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        c:/Users/ymmit/github/Terraform/src/github.com/hashicorp/terraform/plugin/resource_provider.go:505 +0x75
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: reflect.Value.call(0xc0000f3080, 0xc00013c0f8, 0x13, 0xfd163a, 0x4, 0xc000473f18, 0x3, 0x3, 0xc00006a180, 0xdf15e0, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        C:/Go/src/reflect/value.go:447 +0x45b
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: reflect.Value.Call(0xc0000f3080, 0xc00013c0f8, 0x13, 0xc000473f18, 0x3, 0x3, 0xc000117920, 0x0, 0x0)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        C:/Go/src/reflect/value.go:308 +0xab
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: net/rpc.(*service).call(0xc000134200, 0xc000144190, 0xc0003e4578, 0xc0003e4590, 0xc000109380, 0xc0004986a0, 0xdf1820, 0xc00013a4c0, 0x16, 0xdf1860, ...)
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        C:/Go/src/net/rpc/server.go:384 +0x155
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe: created by net/rpc.(*Server).ServeCodec
2019-07-20T09:33:50.718+0800 [DEBUG] plugin.terraform-provider-vra7.exe:        C:/Go/src/net/rpc/server.go:481 +0x485
2019/07/20 09:33:50 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [unexpected EOF]
2019/07/20 09:33:50 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [unexpected EOF]
2019/07/20 09:33:50 [TRACE] [walkValidate] Exiting eval tree: vra7_deployment.my_vra7_deployment
2019/07/20 09:33:50 [TRACE] dag/walk: walking "provider.vra7 (close)"
2019/07/20 09:33:50 [TRACE] vertex 'root.provider.vra7 (close)': walking
2019/07/20 09:33:50 [TRACE] vertex 'root.provider.vra7 (close)': evaluating
2019/07/20 09:33:50 [TRACE] [walkValidate] Entering eval tree: provider.vra7 (close)
2019/07/20 09:33:50 [TRACE] root: eval: *terraform.EvalCloseProvider
2019/07/20 09:33:50 [TRACE] [walkValidate] Exiting eval tree: provider.vra7 (close)
2019/07/20 09:33:50 [TRACE] dag/walk: walking "meta.count-boundary (count boundary fixup)"
2019/07/20 09:33:50 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': walking
2019/07/20 09:33:50 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': evaluating
2019/07/20 09:33:50 [TRACE] [walkValidate] Entering eval tree: meta.count-boundary (count boundary fixup)
2019/07/20 09:33:50 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundaryGlobal
2019/07/20 09:33:50 [TRACE] [walkValidate] Exiting eval tree: meta.count-boundary (count boundary fixup)
2019/07/20 09:33:50 [TRACE] dag/walk: walking "root"
2019/07/20 09:33:50 [TRACE] vertex 'root.root': walking
2019/07/20 09:33:50 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-07-20T09:33:50.728+0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-07-20T09:33:50.733+0800 [DEBUG] plugin: plugin process exited: path=C:\Users\ymmit\github\Terraform\bin\terraform-provider-vra7.exe

**Comment by hobovirtual** [comment]
Hi @ymmit85 

I would suggest to use the official provider that you can find here https://github.com/terraform-providers/terraform-provider-vra7 and see if you still get the error.

Thanks!

**Comment by ymmit85** [comment]
Thanks @hobovirtual ! I totally missed that version!
