### ISSUE TITLE
terraform apply fails: *terraform.EvalValidateResource, err: Warnings: []. Errors: [unexpected EOF]

### ISSUE THREAD

**Issue by eolix** [vmware-archive/legacy-terraform-provider-vra7#50]
Terraform v0.11.0
go version go1.10.2 linux/amd64

Compiles without errors, but when running "terraform apply", we get this error:

```
Error: vra7_resource.vra7-plugin-test-01: unexpected EOF


panic: Unknown validation type: 6
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: goroutine 55 [running]:
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.validateMapValues(0xd9018a, 0x16, 0xc4203f55c0, 0xc420428e10, 0xc4203f55c0, 0xc4203e04a8, 0x195, 0xc42007b308, 0x412f8c, 0xc4203d7b30)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:1450 +0xb94
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateMap(0xc4203f4570, 0xd9018a, 0x16, 0xc0e120, 0xc4203dd360, 0xc420428e10, 0xc4203f5440, 0x0, 0xc4203f5590, 0xd9018a, ...)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:1402 +0x25e
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateType(0xc4203f4570, 0xd9018a, 0x16, 0xc0e120, 0xc4203dd360, 0xc420428e10, 0xc4203f5440, 0x15, 0x0, 0x0, ...)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:1601 +0x5cc
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validate(0xc4203f4570, 0xd9018a, 0x16, 0xc420428e10, 0xc4203f5440, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:1260 +0x1e8
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.validateObject(0xc4203f4570, 0x0, 0x0, 0xc4203f4570, 0xc4203f5440, 0xc4203d7490, 0x40f96f, 0xd13c00, 0xcbdb20, 0xc4203d7490, ...)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:1498 +0x1bf
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.schemaMap.Validate(0xc4203f4570, 0xc4203f5440, 0xd88248, 0xc420402d30, 0xd, 0xc4203f5601, 0xd13c00, 0xc4203f5680)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/schema.go:607+0x46
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Resource).Validate(0xc4203da930, 0xc4203f5440, 0xc420402d30, 0xd, 0xc4203fc3c8, 0x1, 0xc420380a48, 0x4124a8)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/resource.go:270 +0x42
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/helper/schema.(*Provider).ValidateResource(0xc4203da9a0, 0xc420402d30, 0xd, 0xc4203f5440, 0xc4203d7490, 0xc42008b0e0, 0xc420380b38, 0x411c59, 0xc4203f56b0, 0x30)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0x1a7
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ValidateResource(0xc4203dc620, 0xc4203dd0e0, 0xc4203f5620, 0x0, 0x0)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /home/patrik/programming/terraform-provider-vra7/src/github.com/hashicorp/terraform/plugin/resource_provider.go:502 +0x6e
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: reflect.Value.call(0xc42008b0e0, 0xc4200ba918, 0x13, 0xd7fd3d, 0x4, 0xc420380f18, 0x3, 0x3, 0xc4203d00c0, 0x20002,...)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /usr/local/go/src/reflect/value.go:447 +0x969
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7: reflect.Value.Call(0xc42008b0e0, 0xc4200ba918, 0x13, 0xc42005c718, 0x3, 0x3, 0xc4203d4060, 0x7df1fb, 0x1)
2018-05-15T16:26:14.489+0200 [DEBUG] plugin.terraform-provider-vra7:    /usr/local/go/src/reflect/value.go:308 +0xa4
2018-05-15T16:26:14.490+0200 [DEBUG] plugin.terraform-provider-vra7: net/rpc.(*service).call(0xc4201cacc0, 0xc4200bd4a0, 0xc4202da7b0, 0xc4202da7c0, 0xc420188c00, 0xc4203dcba0, 0xbf2800, 0xc4203dd0e0, 0x16, 0xbf2840, ...)
2018-05-15T16:26:14.490+0200 [DEBUG] plugin.terraform-provider-vra7:    /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018-05-15T16:26:14.490+0200 [DEBUG] plugin.terraform-provider-vra7: created by net/rpc.(*Server).ServeCodec
2018-05-15T16:26:14.490+0200 [DEBUG] plugin.terraform-provider-vra7:    /usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/05/15 16:26:14 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [unexpected EOF]
2018/05/15 16:26:14 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [unexpected EOF]
2018/05/15 16:26:14 [TRACE] [walkValidate] Exiting eval tree: vra7_resource.vra7-plugin-test-01
2018-05-15T16:26:14.491+0200 [DEBUG] plugin: plugin process exited: path=/home/patrik/devops/dap-core/devops/terraform/WIP-tst.lab4/terraform-provider-vra7
2018/05/15 16:26:14 [TRACE] dag/walk: walking "meta.count-boundary (count boundary fixup)"
2018/05/15 16:26:14 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': walking
2018/05/15 16:26:14 [TRACE] dag/walk: walking "provider.vra7 (close)"
2018/05/15 16:26:14 [TRACE] vertex 'root.provider.vra7 (close)': walking
2018/05/15 16:26:14 [TRACE] vertex 'root.meta.count-boundary (count boundary fixup)': evaluating
2018/05/15 16:26:14 [TRACE] vertex 'root.provider.vra7 (close)': evaluating
2018/05/15 16:26:14 [TRACE] [walkValidate] Entering eval tree: provider.vra7 (close)
2018/05/15 16:26:14 [TRACE] root: eval: *terraform.EvalCloseProvider
2018/05/15 16:26:14 [TRACE] [walkValidate] Exiting eval tree: provider.vra7 (close)
2018/05/15 16:26:14 [TRACE] [walkValidate] Entering eval tree: meta.count-boundary (count boundary fixup)
2018/05/15 16:26:14 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundaryGlobal
2018/05/15 16:26:14 [TRACE] [walkValidate] Exiting eval tree: meta.count-boundary (count boundary fixup)
2018/05/15 16:26:14 [TRACE] dag/walk: walking "root"
2018/05/15 16:26:14 [TRACE] vertex 'root.root': walking
2018/05/15 16:26:14 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-05-15T16:26:14.492+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Any similar issues?

**Comment by virajindasrao** [comment]
@eolix It would be helpful if you can provide your terraform config file.

**Comment by eolix** [comment]
@virajindasrao 
```
########### WORK IN PROGRESS - DO NOT USE ############

variable "vrealize_password" {}
variable "vrealize_user" {}

provider "vra7" {
  username = "${var.vrealize_user}"
  password = "${var.vrealize_password}"
  tenant   = "vsphere.local"
  host     = "https://******.*****.******.*******"
}

variable "masters" {
  default = 1
}

resource "vra7_resource" "vra7-plugin-test-01" {
  count      = "${var.masters}"
  catalog_id = "50b9ae39-06f9-42e5-bfbd-ea7f90fb00a4"
  name       = "vra7-plugin-test-01"

  resource_configuration {
    Machine.description                                     = "vra7-plugin-test-01"
    Machine.cpu                                             = 2
    Machine.memory                                          = 8192
    Machine.storage                                         = 50
    Machine.ExternalWFStubs.MachineProvisioned.sshKey_value = "ssh-rsa pubkey root@tst.lab2"
    Machine.VirtualMachine.Disk0.Size                       = 80
    Machine.VirtualMachine.Disk1.Size                       = 80
    Machine.VirtualMachine.Disk2.Size                       = 80
  }

  deployment_configuration = {
    reasons     = "test-reason"
    description = "test-description"
  }
}

**Comment by virajindasrao** [comment]
Kindly use 'dep ensure' before compiling the binary.
For more information kindly refer [issue#52](https://github.com/vmware/terraform-provider-vra7/issues/52)

**Comment by mihail-i4v** [comment]
Faced the same error, compiled a new vra7 binary following the instructions in https://github.com/vmware/terraform-provider-vra7 and that fixed it.
